import React from "react";
import {
  View,
  StyleSheet,
  Text,
  ScrollView,
} from "react-native";
import { LinearGradient } from "expo-linear-gradient";

export default function DisclaimerSection() {
  return (
    <View style={styles.container}>
      <LinearGradient
        colors={["rgba(255, 215, 0, 0.2)", "rgba(255, 140, 0, 0.1)"]}
        style={styles.gradientBackground}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 1 }}
      >
        <View style={styles.headerContainer}>
          <Text style={styles.disclaimerTitle}>⚠️ Important Disclaimer</Text>
        </View>
        
        <ScrollView style={styles.scrollContainer} showsVerticalScrollIndicator={false}>
          <View style={styles.contentContainer}>
            <Text style={styles.disclaimerText}>
              <Text style={styles.boldText}>Divine Sarathi</Text> is an AI-powered spiritual guidance platform 
              designed to provide general spiritual insights and support based on ancient wisdom traditions.
            </Text>
            
            <Text style={styles.disclaimerText}>
              • This app is <Text style={styles.boldText}>not a substitute</Text> for professional medical, 
              psychological, or legal advice.
            </Text>
            
            <Text style={styles.disclaimerText}>
              • Responses are generated by AI and should be considered as 
              <Text style={styles.boldText}> general guidance only</Text>.
            </Text>
            
            <Text style={styles.disclaimerText}>
              • For serious personal, health, or legal matters, please consult 
              qualified professionals.
            </Text>
            
            <Text style={styles.disclaimerText}>
              • Your privacy is important to us. Personal information shared will be handled 
              with care and respect.
            </Text>
          </View>
        </ScrollView>
      </LinearGradient>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    borderRadius: 15,
    overflow: "hidden",
    marginHorizontal: 20,
    marginVertical: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  gradientBackground: {
    flex: 1,
    padding: 15,
  },
  headerContainer: {
    alignItems: "center",
    marginBottom: 10,
  },
  disclaimerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#8B1538",
    textAlign: "center",
    textShadowColor: "rgba(255, 255, 255, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
    gap: 8,
  },
  disclaimerText: {
    fontSize: 13,
    color: "#2C1810",
    lineHeight: 18,
    textAlign: "left",
  },
  boldText: {
    fontWeight: "bold",
    color: "#8B1538",
  },
});
